config/routes.rb
ToDoApp::Application.routes.draw do
  devise_for :users 

  resources :users do
    resources :todos
  end

  root "todos#index"

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  validates :item, presence: true

  def overdue_days
    ((Time.now - self.duedate)/60/60/24).round
  end

  def self.find_todos(user)
    self.where(user_id: user.id).where(done: false).where("duedate >= ?", Time.now.midnight + 1.day).to_a
  end

  def self.find_todays(user)
    self.where(user_id: user.id).where(done: false).where(duedate: Time.now.midnight..(Time.now.midnight + 1.day)).to_a
  end

  def self.find_overdues(user)
    self.where(user_id: user.id).where(done: false).where("duedate <= ?", Time.now.midnight - 1.day).to_a
  end

  def self.todo_count(user)
    todo_count_array = []
    (1..5).each do |days_ago|
      todo_count_array << self.where(user_id: user.id).where(duedate: Time.now.midnight - days_ago.day).to_a.length
    end
    todo_count_array.reverse
  end

  def self.done_count(user)
    done_count_array = []
    (1..5).each do |days_ago|
      done_count_array << self.where(user_id: user.id).where(done: true).where(updated_at: Time.now.midnight - days_ago.day).to_a.length
    end
    done_count_array.reverse
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todos

  # def self.short_search(searching)
  #   short_search_results = []
  #   searching.each do |dun|
  #     if dun.item.length > 12
  #       short_search_results << dun.item.truncate(9)
  #     else
  #       short_search_results << dun.item 
  #     end
  #   end
  #   short_search_results
  # end

  def self.find_done(user)
    searching = Todo.where(user_id: user.id).where(done: true).to_a
    # results = self.short_search(searching)
    filler = [{item: 'bake cakes'}, {item: 'lift weights'}, {item: 'write lists'}, {item: 'eat veggies'}, {item: 'drink water'}]
    i = 4
    while searching.length < 5
      searching << filler[i]
      i -= 1
    end
    searching[-5..-1]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @user = current_user
    @todo = @user.todos.new
    @todays = Todo.find_todays(@user)
    @todos = Todo.find_todos(@user)
    @overdue = Todo.find_overdues(@user)
    @done = User.find_done(@user)
    @todo_count = Todo.todo_count(@user)
    @done_count = Todo.done_count(@user)
    gon.todo_count = Todo.todo_count(@user)
    gon.done_count = Todo.done_count(@user)
  end

  def create
    @todo = Todo.new(todo_params)
    respond_to do |format|
      if @todo.save
        format.js { render layout: false }
      else
        {:alert => "Something serious happened."}
      end
    end
  end

  def new
  end

  def edit
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.done = true
    @user = current_user
    @done = User.find_done(@user)
    respond_to do |format|
      if @todo.save
        format.js { render layout: false }
      end
    end
  end

  def destroy
    @user = current_user
    @todos = Todo.find_todos(@user)
    @todo = Todo.destroy(params[:id])
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def show
  end

  private

    def todo_params
      params.require(:todo).permit(:item, :duedate, :done, :user_id)  
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %title ToDoApp
    = include_gon
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %nav.top-bar
      %section.top-bar-section
      // Right Nav Section
      %section.top-bar-section
        - if user_signed_in?
          %ul.right
            %li= link_to 'Edit profile', edit_user_registration_path
            %li= link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %ul.right
            %li= link_to "Sign up", new_user_registration_path
            %li= link_to "Login", new_user_session_path

    - if notice || alert
      .row
        .flash.small-8.medium-4.small-centered.medium-centered.columns  
          %p.notice
            = notice
          %p.alert
            = alert
    = yield

app/views/todos/_done.html.haml
.small-6.medium-2.columns
  .done_items
    %h4.medium-12.medium-centered.columns
      = todo[:item].truncate 13

app/views/todos/_form.html.haml
%fieldset
  = simple_form_for([@user, @todo], remote: true) do |f|
    = f.input :item, as: :string, placeholder: 'At what are you going to fail?', label: false
    = f.input :duedate, as: :date, label: false, order: [:month, :day, :year]
    = f.hidden_field :done, value: false
    = f.hidden_field :user_id, value: @user.id
    = f.button :submit

app/views/todos/_newtodo.html.haml
.todo{"data-todo-id" => "#{todo.id}"}
  %h4= todo.item
  %h5= todo.duedate.strftime("%B %e, %Y")
  = link_to "Done?", user_todo_path(current_user.id, todo.id), :method => :put, :remote => :true
  ||
  = link_to "I'm not doing that.", user_todo_path(current_user.id, todo.id), :method => :delete, :confirm => "Quitting already?", :remote => :true

app/views/todos/_pastdo.html.haml
.overdue{"data-todo-id" => "#{overdue.id}"}  
  %h4= overdue.item
  %h5 
    Overdue by
    = pluralize(overdue.overdue_days, "day")
  = link_to 'Finally done?', user_todo_path(current_user.id, overdue.id), :method => :put, :remote => :true
  ||
  = link_to 'Giving up?', user_todo_path(current_user.id, overdue.id), :method => :delete, :confirm => "Quitting already?", :remote => :true

app/views/todos/create.js.erb
(function () {
  var templateHtml = "<%= j render(partial: 'newtodo', locals: {todo: @todo}) %>";
  $('.todolist').prepend(templateHtml);
  $('#todo_item').val('');
})();

app/views/todos/destroy.js.erb
$('div[data-todo-id=<%= @todo.id %>]').remove();

app/views/todos/index.html.haml
.row
  .small-12.medium-8.columns
    %header
      %h1 done git it

.row
  .small-12.medium-4.columns
    =render "form"

    - if @todo.errors.any?
      #error_explanation
        %h2= pluralize(@todo.errors.count, "error")
        prohibited this git it from being saved:
        - ul
        = @todo.errors.full_messages.each do |msg|
          %li= msg

  .small-12.medium-4.columns
    %h3 
      To Do
      .todaylist
        - @todays.each do |todo|
          = render "newtodo", todo: todo  
      .todolist
        - @todos.each do |todo|
          = render "newtodo", todo: todo
  
  .small-12.medium-4.columns
    %h3
      Past Due
      - @overdue.each do |overdue|
        = render "pastdo", overdue: overdue

.row
  .small-12.medium-12.columns.done
    %h3.medium-2.columns 
      Done ||
    - @done.each do |todo|
      = render "done", todo: todo

.row
  .small-12.medium-12.small-centered.medium-centered.columns
    %canvas#myChart{height: "150px", width: "800px"}

app/views/todos/update.js.erb
var $item = $('div[data-todo-id=<%= @todo.id %>] h4:first-child');
$('.done_items:last').html($item);
$('div[data-todo-id=<%= @todo.id %>]').remove();